### ISSUE TITLE
Vertaisarviointi

### ISSUE THREAD

**Issue by tjuslin** [oheinonen/tiralabra#1]
# Vertaisarviointi 1

Projekti kloonattu pe 2.12 noin klo 12. Tutustuin hieman projektiin jo tuolloin, mutta varsinaisen vertaisarvioinnin teen nyt 3.12. Projektiin ei ole tehtyä muutoksia eilisen jälkeen, joten käytössä on ohjelman uusin versio.

---

Hei!

Sain näköjään vertaisarvioitavaksi projektin samasta aiheesta kuin oma projektini, joten ainakin aihe on tuttu. Toteutuskin on itse editointietäisyyksien laskemisen osalta pitkälti samanlainen, eli Steve Hanovin blogissa esitettyyn algoritmiin perustuva ratkaisu.

## Rakenne ja koodi yleisesti

Rakenteeltaan ohjelma vaikuttaa hyvältä. Koodi on helppolukuista ja jaettu järkevästi eri moduuleihin. Rakenteen puolesta ainoa asia, josta voisin nipottaa, on käyttöliittymän ja muun koodin sekoittaminen keskenään. Käyttöliittymä on toki todella yksinkertainen, mutta pyrkisin silti siistimään `SpellCorrector`-luokan `run`-metodia eriyttämällä käyttöliittymäkoodin muusta koodista. 

## Ohjelman ajaminen ja manuaalinen testaus

Ohjelma toimii joillain syötteillä nopeasti ja antaa hyviä ehdotuksia, mutta toiset syötteet saa ohjelman helposti jumiin (ja oman ubuntu-koneeni :D). Tutkin tässä vaiheessa koodia tarkemmin ja ymmärtääkseni ongelma johtuu yksinkertaisesti siitä, että eri permutaatioiden määrä (`candidate_sentences`) kasvaa helposti valtavaksi. Ongelma ymmärrettävästi pahenee kun maksimietäisyyden (`MAX_TYPOS_IN_WORD`) arvoa kasvattaa. Jos maksimietäisyyden arvoksi laittaa esimerkiksi kaksi, lyhyidenkin lauseiden korjaaminen menee aika mahdottomaksi. Lisäksi mitä lyhyempiä sanoja lauseessa esiintyy, sitä enemmän korjausehdotuksia sanoille löytyy, mikä edelleen osaltaan pahentaa ongelmaa.

Esimerkkejä syötteistä, jotka saivat koneeni kyykkyyn:

```
MAX_TYPOS_IN_WORD = 1
this is a longer sentence that makes it crash

MAX_TYPOS_IN_WORD = 2
men in black
```

Sanoille *men* ja *in* löytyy yli 500 korjausvaihtoehtoa maksimietäisyyden ollessa kaksi. Näistä tulee aika hurja määrä permutaatioita.

---

Toinen ongelma johon törmäsin testatessa on se, että jos jollekin sanalle ei löydy yhtään korjausehdotusta, ohjelma ei korjaa mitään sanoista. Itse palautan tässä tilanteessa sanan sellaisenaan tulostettavaksi.

Esimerkkisyöte: 
```
this is a snetence tätäeilöydy
-> Lausetta ei löytynyt
```

---

## Loppumietelmiä

Mietin tässä vaiheessa, miten mielekästä on ylipäätään yrittää korjata lauseita (tai sanoja), jotka ovat jo valmiiksi kirjoitettu oikein. Omassa ratkaisussani tarkistan aluksi löytyvätkö sanat jo sanakirjasta ja jos näin on, niin palautan ne tulostettavaksi sellaisenaan. Dokumentaatiossa mainitset, että haluat ohjelman ottavan myös kontekstin huomioon, mutta mielestäni tämä ei niinkään enää liity pelkästään kirjoitusvirheiden korjaamiseen ja osoittautuu ehkä liian työlääksi ja monimutkaiseksi tämän kurssin puitteissa. Korjausehdotukset näyttäisivät perustuvan tällä hetkellä vahvasti nimenomaan bigrammeihin, mutta itseltä ikävä kyllä loppuu tiedot ja taidot antaa neuvoja suorituskyvyn parantamiseksi tässä asiassa.

Toivottavasti tästä oli hyötyä! Projekti on hyvässä kuosissa ja löydät varmasti ratkaisut näihin ongelmiin. Tsemppiä!

**Comment by oheinonen** [comment]
Kiitos paljon kattavasta palautteesta! Ja erittäin hyvä huomio tuo että tietyillä syötteillä ohjelma crashaa -- loogista mutta eipä tullut itse vielä kokeiltua. Olet varmaan oikeassa, että kurssin puitteissa syytä laskea hieman ambitiotasoa ja keskittyä siihen että jokaiselle annetulle lauseelle saadaan palautettua lause.  Tästä tuli hyviä korjausehdotuksia tälle viikolle!
