### ISSUE TITLE
Vertaisarviointi

### ISSUE THREAD

**Issue by heliparv** [oheinonen/tiralabra#2]
Repositorio kloonattu 10.12. klo 14:30

Ohjelma vaikuttaa toimivan oikein hyvin ja on miellyttävä käyttää. Valittu ongelma on haastava, joten olen vaikuttunut siitä, miten järkeviä ehdotuksia se antaa.

Ohjelmassa voisi olla tarkistus sille, mitkä syötteen kirjaimista ovat isoja ja ne voisi palauttaa isoina, vaikka tarkistus tehdäänkin pienillä kirjaimilla. Heti ensimmäinen lause jonka syötin oli oikein kirjoitettu “Hefty cat eats tuna” ja ohjelman ehdottama ensimmäinen korjaus oli “lefty cat eats tuna” ennen kuin toisena korjauksena sain “hefty cat eats tuna”.

Käyttöliittymän suomenkielisyys hämmentää hieman kun tarkistetaan englanninkielisiä lauseita. Ohje voisi olla käyttöliittymässä “Syötä englanninkielinen lause jonka oikeinkirjoituksen…” tai sitten käyttöliittymä voisi olla englanniksi.

Koodin laatu näyttää hyvältä. Funktiot ovat mukavasti suupalan kokoisia ja vaikuttavat helposti hahmotettavilta. Eri toiminnallisudet on jaettu eri luokkiin ja koodin dokumentaatio on kunnossa. Ei tässä oikein voi muuta sanoa kuin että jatka samaan malliin.

**Comment by oheinonen** [comment]
Kiitokset palautteesta ja parannusehdotuksista!
